//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movie_express
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bancoEntities1 : DbContext
    {
        public bancoEntities1()
            : base("name=bancoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_NOTIC> TB_NOTIC { get; set; }
        public DbSet<TB_PDPROD> TB_PDPROD { get; set; }
        public DbSet<TB_PEDIDO> TB_PEDIDO { get; set; }
        public DbSet<TB_PROD> TB_PROD { get; set; }
        public DbSet<TB_USER> TB_USER { get; set; }
    }
}
