//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movie_express
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NOTIC
    {
        public int NT_ID { get; set; }
        public string NT_TITULO { get; set; }
        public Nullable<System.DateTime> NT_DTPUBL { get; set; }
        public string NT_CORPO { get; set; }
        public Nullable<int> NT_CURTID { get; set; }
    }
}
