//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movie_express
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROD
    {
        public TB_PROD()
        {
            this.TB_PDPROD = new HashSet<TB_PDPROD>();
        }
    
        public int PROD_ID { get; set; }
        public string PROD_TITULO { get; set; }
        public decimal PROD_PRECO { get; set; }
        public string PROD_GENERO { get; set; }
        public Nullable<int> PROD_ANOLAN { get; set; }
        public string PROD_SINOPS { get; set; }
        public Nullable<int> PROD_IMDB { get; set; }
        public int PROD_QTDEST { get; set; }
        public string PROD_FOTO { get; set; }
    
        public virtual ICollection<TB_PDPROD> TB_PDPROD { get; set; }
    }
}
