//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movie_express
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PDPROD
    {
        public int PEDI_ID { get; set; }
        public int PROD_ID { get; set; }
        public int PDPR_QTD { get; set; }
    
        public virtual TB_PEDIDO TB_PEDIDO { get; set; }
        public virtual TB_PROD TB_PROD { get; set; }
    }
}
