//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movie_express
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER
    {
        public TB_USER()
        {
            this.TB_PEDIDO = new HashSet<TB_PEDIDO>();
        }
    
        public int US_ID { get; set; }
        public bool US_ADM { get; set; }
        public string US_NOME { get; set; }
        public string US_CPF { get; set; }
        public string US_RG { get; set; }
        public System.DateTime US_NASC { get; set; }
        public string US_EMAIL { get; set; }
        public string US_SENHA { get; set; }
        public string US_TEL { get; set; }
        public string US_CEL { get; set; }
    
        public virtual ICollection<TB_PEDIDO> TB_PEDIDO { get; set; }
    }
}
